---
- name: VACUUM ANALYZE systemd service and timer unit files
  with_items:
  - "postgres_vacuum.service"
  - "postgres_vacuum.timer"
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    owner: root
    group: root

- name: Enable and start the VACUUM ANALYZE timer
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: postgres_vacuum.timer
    enabled: true
    state: started
...
